baseURL = "https://blog.lacolaco.net/"
languageCode = "ja-JP"
title = "lacolaco/tech"
enableEmoji = true
googleAnalytics = "G-0BEKSBSM5X"
#disqusShortName = "blog-lacolaco"
copyright = "Â© 2020 lacolaco.net"
paginate = 1000000000
hasCJKLanguage = true
rssLimit = 10

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:filename"

[markup.highlight]
  # guessSyntax = false
  # noClasses = false
  codeFences = false
  # style = "github"
[markup.goldmark.renderer]
    unsafe = true

[minify]
  disableXML = true
  