baseURL = "https://blog.lacolaco.net/"
languageCode = "ja-JP"
title = "<output type=\"text\">"
enableEmoji = true
googleAnalytics = "UA-52362663-4"
copyright = "Â© 2020 lacolaco.net"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:slug"