name: shutdown-preview

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  shutdown-preview:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-preview')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
      pull-requests: write
    environment: development
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Google Auth
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          workload_identity_provider: 'projects/348931464772/locations/global/workloadIdentityPools/github-actions-pool/providers/github-deploy'
          service_account: 'github-actions@blog-lacolaco-net.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      # https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration?hl=ja#remove-tags
      - name: Remove revision tag from Cloud Run service
        run: |
          gcloud run services update-traffic web --region asia-northeast1 --remove-tags pr-${{ github.event.number }}
